/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ddr;

import org.junit.Test;
import static org.junit.Assert.*;

import ddr.model.Highscore;

public class AppTest {
    @Test 
    public void newHighScore() {
        Highscore high = new Highscore();
        int big = 99;
        high.addHighscore(big);
        assertEquals(true, high.getHighscores().get(0) == big);
    }
}
